services:
  label_studio:
    image: heartexlabs/label-studio:latest
    container_name: label_studio
    ports:
      - '8080:8080'
    volumes:
      - ./label-studio:/label-studio
    environment:
      - LABEL_STUDIO_HOST=http://14.161.17.92:8080 # using IPv4
      - LABEL_STUDIO_PORT=8080
    networks:
      - minio_net
networks:
  minio_net:
    driver: bridge
    name: minio_net