services:
  label_studio:
    image: heartexlabs/label-studio:latest
    container_name: label_studio
    ports:
      - '8080:8080'
    volumes:
      - ./label-studio/mydata:/label-studio/data
    environment:
      - LABEL_STUDIO_HOST=http://localhost:8080 # using IP Public
      - LABEL_STUDIO_PORT=8080
    networks:
      - minio_net
networks:
  minio_net:
    driver: bridge
    name: minio_net